package com.rockthejvm.reviewboard.components

import scala.scalajs.*
import scala.scalajs.js.* // js native
import scala.scalajs.js.annotation.* // will allow cross-compilation of scala code to JS

///////////////
// BOILER PLATE
// TO EXPOSE SOME OF `MOMENT.JS` FUNCTIONALITIES

// JavaScript interop layer - defines Scala facades for Moment.js library
// allowing seamless invocation of JavaScript functions from Scala.js code

// JavaScript interop layer using Scala.js facades to bridge Moment.js functionality.
// The @js.native annotations create compile-time bindings that map Scala method calls
// to their corresponding JavaScript implementations. 
// At runtime, calls to these Scala methods are translated directly into 
// JavaScript function invocations without overhead.
// This enables type-safe access to external JavaScript libraries from Scala.js code.

@js.native
@JSGlobal // make the class accessible in the global scope of the js code generated by scalajs
class Moment extends  js.Object {
  def format(): String = js.native
  def fromNow(): String = js.native
}


// require "moment";
@js.native
@JSImport("moment", JSImport.Default)
object MomentLib extends js.Object {
  def unix(millis: Long): Moment = js.native

}

///////////////
// the API used in our app
object Time {
  def unix2humanReadable(millis: Long): String =
    MomentLib.unix(millis / 1000).fromNow()

  def past(millis: Long) =
    new Date().getTime.toLong - millis
}

